"""Initial migration

Revision ID: 0a402ad36e49
Revises: 
Create Date: 2025-12-16 18:51:17.413950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a402ad36e49'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('well',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('start_measured_depth', sa.Float(), nullable=True),
    sa.Column('end_measured_depth', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_well_id'), 'well', ['id'], unique=False)
    op.create_table('curve',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('well_id', sa.Integer(), nullable=False),
    sa.Column('measured_depth', sa.Float(), nullable=True),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['well_id'], ['well.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curve_id'), 'curve', ['id'], unique=False)
    op.create_table('effective_formation_thickness',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('well_id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('absolute_depth', sa.Float(), nullable=True),
    sa.Column('thickness', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['well_id'], ['well.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_effective_formation_thickness_id'), 'effective_formation_thickness', ['id'], unique=False)
    op.create_table('formation_thickness',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('well_id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('absolute_depth', sa.Float(), nullable=True),
    sa.Column('thickness', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['well_id'], ['well.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_formation_thickness_id'), 'formation_thickness', ['id'], unique=False)
    op.create_table('welltrack',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('well_id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('absolute_depth', sa.Float(), nullable=True),
    sa.Column('measured_depth', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['well_id'], ['well.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_welltrack_id'), 'welltrack', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_welltrack_id'), table_name='welltrack')
    op.drop_table('welltrack')
    op.drop_index(op.f('ix_formation_thickness_id'), table_name='formation_thickness')
    op.drop_table('formation_thickness')
    op.drop_index(op.f('ix_effective_formation_thickness_id'), table_name='effective_formation_thickness')
    op.drop_table('effective_formation_thickness')
    op.drop_index(op.f('ix_curve_id'), table_name='curve')
    op.drop_table('curve')
    op.drop_index(op.f('ix_well_id'), table_name='well')
    op.drop_table('well')
    # ### end Alembic commands ###
